"""add activities and activity_files tables

Revision ID: 58e6260250a7
Revises: a1b2c3d4e5f6
Create Date: 2026-06-11 04:11:21.867232
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
import sqlmodel.sql.sqltypes  # noqa: F401

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58e6260250a7'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('user_id', 'activity_id', name='uq_activities_user_id_activity_id')
    )
    op.create_table('activity_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_files_activity_id_activities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_files')),
    sa.UniqueConstraint('activity_id', 'file_format', name='uq_activity_files_activity_id_file_format')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_files')
    op.drop_table('activities')
    # ### end Alembic commands ###
